# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from rengars_marketplace import util
from rengars_marketplace.models.BaseModel import BaseModel


class JobApplicationState(BaseModel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NEW = "NEW"
    ACTIVE = "ACTIVE"
    REJECTED = "REJECTED"
    ACCEPTED = "ACCEPTED"
    WITHDRAWN = "WITHDRAWN"

    def __init__(self):  # noqa: E501
        """JobApplicationState - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'JobApplicationState':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JobApplicationState of this JobApplicationState.  # noqa: E501
        :rtype: JobApplicationState
        """
        return util.deserialize_model(dikt, cls)
