# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from rengars_marketplace import util
from rengars_marketplace.models.BaseModel import BaseModel
from rengars_marketplace.models.JobApplicationState import JobApplicationState  # noqa: F401,E501


class JobApplicationStateDto(BaseModel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: JobApplicationState = None):  # noqa: E501
        """JobApplicationStateDto - a model defined in Swagger

        :param state: The state of this JobApplicationStateDto.  # noqa: E501
        :type state: JobApplicationState
        """
        self.swagger_types = {
            'state': JobApplicationState
        }

        self.attribute_map = {
            'state': 'state'
        }
        self._state = state

    @classmethod
    def from_dict(cls, dikt) -> 'JobApplicationStateDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JobApplicationStateDto of this JobApplicationStateDto.  # noqa: E501
        :rtype: JobApplicationStateDto
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> JobApplicationState:
        """Gets the state of this JobApplicationStateDto.


        :return: The state of this JobApplicationStateDto.
        :rtype: JobApplicationState
        """
        return self._state

    @state.setter
    def state(self, state: JobApplicationState):
        """Sets the state of this JobApplicationStateDto.


        :param state: The state of this JobApplicationStateDto.
        :type state: JobApplicationState
        """

        self._state = state
