# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from swagger_server import util
from swagger_server.models.base_model_ import Model


class JobOfferState(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    OPEN = "OPEN"
    HIRED = "HIRED"
    WITHDRAWN = "WITHDRAWN"

    def __init__(self):  # noqa: E501
        """JobOfferState - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'JobOfferState':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JobOfferState of this JobOfferState.  # noqa: E501
        :rtype: JobOfferState
        """
        return util.deserialize_model(dikt, cls)
