# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from rengars_marketplace import util
from rengars_marketplace.models.BaseModel import BaseModel
from rengars_marketplace.models.JobOfferState import JobOfferState  # noqa: F401,E501


class UpdateJobOfferDto(BaseModel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: JobOfferState = None):  # noqa: E501
        """UpdateJobOfferDto - a model defined in Swagger

        :param state: The state of this UpdateJobOfferDto.  # noqa: E501
        :type state: JobOfferState
        """
        self.swagger_types = {
            'state': JobOfferState
        }

        self.attribute_map = {
            'state': 'state'
        }
        self._state = state

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateJobOfferDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateJobOfferDto of this UpdateJobOfferDto.  # noqa: E501
        :rtype: UpdateJobOfferDto
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> JobOfferState:
        """Gets the state of this UpdateJobOfferDto.


        :return: The state of this UpdateJobOfferDto.
        :rtype: JobOfferState
        """
        return self._state

    @state.setter
    def state(self, state: JobOfferState):
        """Sets the state of this UpdateJobOfferDto.


        :param state: The state of this UpdateJobOfferDto.
        :type state: JobOfferState
        """
        if state is None:
            raise ValueError("Invalid value for `state`, must not be `None`")  # noqa: E501

        self._state = state
