# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from rengars_marketplace import util
from rengars_marketplace.models.Model import Model


class UpdateJobApplicationDto(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, note: str = None):  # noqa: E501
        """UpdateJobApplicationDto - a model defined in Swagger

        :param note: The note of this UpdateJobApplicationDto.  # noqa: E501
        :type note: str
        """
        self.swagger_types = {
            'note': str
        }

        self.attribute_map = {
            'note': 'note'
        }
        self._note = note

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateJobApplicationDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateJobApplicationDto of this UpdateJobApplicationDto.  # noqa: E501
        :rtype: UpdateJobApplicationDto
        """
        return util.deserialize_model(dikt, cls)

    @property
    def note(self) -> str:
        """Gets the note of this UpdateJobApplicationDto.


        :return: The note of this UpdateJobApplicationDto.
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note: str):
        """Sets the note of this UpdateJobApplicationDto.


        :param note: The note of this UpdateJobApplicationDto.
        :type note: str
        """

        self._note = note
