name: Build and run flask

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9.4
        uses: actions/setup-python@v1
        with:
          python-version: "3.9.4"
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          ls -a
          python -m pip install --upgrade pip
          pip freeze > requirements.txt
          pip install -r ./requirements.txt

      - name: Run unit tests
        env:
          TESTING: true
        run: |
          pip freeze > ./test-requirements.txt
          pip install -r ./test-requirements.txt
          python -m unittest discover apptest
