name: Build and run flask

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9.4
        uses: actions/setup-python@v1
        with:
          python-version: "3.9.4"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        env:
          TESTING: true
        run: |
          python -m unittest
