# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models.BaseModel import BaseModel


class JobOfferState(BaseModel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    OPEN = "OPEN"
    COMPLETED = "COMPLETED"
    WITHDRAWN = "WITHDRAWN"

    @staticmethod
    def is_readonly(state):
        return state == JobOfferState.COMPLETED or \
               state == JobOfferState.WITHDRAWN
