# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models.BaseModel import BaseModel
from models.JobOfferState import JobOfferState  # noqa: F401,E501

state = 'state'


class UpdateJobOfferDto(BaseModel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, new_state: JobOfferState = None):  # noqa: E501
        """UpdateJobOfferDto - a model defined in Swagger

        :param new_state: The state of this UpdateJobOfferDto.  # noqa: E501
        :type new_state: JobOfferState
        """
        self._data = {
            state: new_state
        }

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateJobOfferDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateJobOfferDto of this UpdateJobOfferDto.  # noqa: E501
        :rtype: UpdateJobOfferDto
        """
        instance = cls()
        instance.state = dikt[state]
        return instance

    @property
    def state(self) -> JobOfferState:
        """Gets the state of this UpdateJobOfferDto.


        :return: The state of this UpdateJobOfferDto.
        :rtype: JobOfferState
        """
        return self._data[state]

    @state.setter
    def state(self, new_state: JobOfferState):
        """Sets the state of this UpdateJobOfferDto.


        :param new_state: The state of this UpdateJobOfferDto.
        :type new_state: JobOfferState
        """
        if new_state is None:
            raise ValueError("Invalid value for `state`, must not be `None`")  # noqa: E501

        self._data[state] = new_state
